### ISSUE TITLE
error FS0192 : internal error : No compiled representation for provided namespace

### ISSUE THREAD

**Issue by deyanp** [bddkickstarter/Gherkin.TypeProvider#3]
Hi,

After upgrading from 6.0.202 -> 6.0.300 we are getting the following compilation error:

`error FS0192 : internal error : No compiled representation for provided namespace [/XxxService/tests/XxxService.UnitTests/XxxService.UnitTests.fsproj]`

Googling brings nothing, so there seems to be something specific to this project which does not work .... Can you help?

Br,
Deyan

**Comment by bddkickstarter** [comment]
Hi Deyan - I'm not sure what version you're talking about as the Gherkin TP only goes up to v 0.1.10.   What did you upgrade?

thanks

Chris

**Comment by deyanp** [comment]
Hi Chris, I meant upgrade of dotnet runtime/SDK ... Br, Deyan

**Comment by picolino** [comment]
Same error. @deyanp any workarounds?
